### PR TITLE
Document new rig bone fitting strategies, UI, and asset subrig creation.

### PR DESCRIPTION
**Pull request by angavrilov**
I'm submitting a pull request to document the new features of MPFB.

Note however, that I changed some of the text assuming https://developer.blender.org/T103074 is soon fixed in Blender 3.5 master as currently intended.

### CODE REVIEW

**Comment by joepal1976** [comment]
Thanks

**Comment by joepal1976** [comment]
I've pushed the build of the website now. Let me know if anything looks strange:

http://static.makehumancommunity.org/mpfb/docs/rigging_mesh_assets.html

**Comment by angavrilov** [comment]
> I've pushed the build of the website now. Let me know if anything looks strange:

Coloring for in-line code string is weird, basically white on white. Search for 'mhmask-subrig' on this page: http://static.makehumancommunity.org/mpfb/docs/rigging_mesh_assets.html

**Comment by joepal1976** [comment]
Yes, that's not good. 

I've updated the css to have code use a black background instead. You may need to force reload the page to see the changes in css.

**Comment by angavrilov** [comment]
I've noticed one more issue: the "bone developer panel" image on the same page does not show. I think it's a problem with case sensitive file paths - I wrote the document on Windows and it wasn't a problem, and it also worked in the GitHub viewer.

**Comment by joepal1976** [comment]
Ok, fixed that too. 

That was a quirk of Hugo rather than the case being wrong per se in the markdown file. Hugo lower-cases all directories on site build. On windows it doesn't matter.

**Pull request merged**
